project:
  type: book
  output-dir: _book

book:
  title: "机器学习Python"
  author: "陆海波"
  date: today
  chapters:
    - index.qmd
    - part: "讲义"
      chapters:
        - week1_lecture.qmd
        - week2_lecture.qmd
        - week3_lecture.qmd
        - week4_lecture.qmd
        - week5_lecture.qmd
        - week6_lecture.qmd
        - week7_lecture.qmd
        - week8_lecture.qmd
    - part: "实验"
      chapters:
        - week1_exercise.qmd
        - week2_exercise.qmd
        - week3_exercise.qmd
        - week4_exercise.qmd
        - week5_exercise.qmd
        - week6_exercise.qmd
        - week7_exercise.qmd
        - week8_exercise.qmd

execute:
  echo: true
  message: false
  warning: false
  error: false
  cache: false

knitr:
  opts_chunk:
    comment: "#>"
    fig.align: "center"
    fig.width: 8
    fig.height: 6
    out.width: "90%"
    dpi: 300
    dev: "ragg_png"

format:
  html:
    theme: cosmo
    css:
      - styles/custom.css
    toc: true
    number-sections: false
    code-fold: false
    callout-appearance: "none"
    message: false
    warning: false
engine: python
